services:
  iql-training:
    build:
      context: .
      dockerfile: Dockerfile
    image: bbugeja95/microrts-agents:iql_latest
    ipc: host
    runtime: nvidia
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY}
      - HTTPS_PROXY=${HTTPS_PROXY}
    env_file:
      - .env
    volumes:
      - ../data:/data
      - ../config:/app/config
      - ../results:/app/_exp
    working_dir: /app/
    command: ${DOCKER_COMMAND}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host