seed: 42
debug: False
device: cuda

eval: {
  eval: False,
  envs_num: 8,
  rollouts: 200,
}

environment: {
  save_dir: _exp,
  project: PhD,
  group: iql,
  name: microrts,
  max_steps: 2000,
  self_play: False,
}

data: {
  buffer_path: "../data/8x8/1v1/replay_buffer_chunked_pristine",
  save_interval: 10000,
  log_interval: 10,
}

iql: {
  model: {
    dropout: 0.1,
    hidden_dim: 256,
    load: False,
    load_path: "C:/Users/bendb/Desktop/Code/cgdt/_exp/2025.01.31/174407-microrts",
  },
  training: {
    train: True,
    iql_tau: 0.7,
    tau: 0.005,
    beta: 3.0,
    discount: 0.99,
    max_timesteps: 2000000,
    vf_lr: 3.0e-4,
    qf_lr: 3.0e-4,
    actor_lr: 3.0e-4,
    batch_size: 64,
    buffer_size: 3000,
    reward_scale: 1.0,
  },
  eval: {
    eval_freq: 5000,
    episodes_num: 10,
    longer_episodes_num: 100,
  }
}